{% set name = "gmshModel" %}
{% set version = "1.0.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gmshModel-{{ version }}.tar.gz
  sha256: 3ef9d59750acc7c73d5322ed5fb16e056147808691a762a890bf214c1ddd90c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - numpy
    - pythonocc-core >=7.4
    - python-gmsh
    - pyvista >=0.24.1
    - meshio >=4, <=5.1.2
    - python >=3.5

test:
  imports:
    - gmshModel

about:
  home: https://github.com/NEFM-TUDresden/GmshModel
  summary: A mesh modeling interface to the Gmsh-Python-API
  license: GPL-3.0-or-later
  license_file: LICENSE
  license_family: GPL
  doc_url: https://gmshmodel.readthedocs.io/
  dev_url: https://github.com/NEFM-TUDresden/GmshModel

extra:
  recipe-maintainers:
    - PhilippMetsch
