{% set name = "gmshModel" %}
{% set version = "1.0.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gmshModel-{{ version }}.tar.gz
  sha256: 4caf7e0b1065a0a178779142c46dd41bc14624c2f3a637572aa80bfe1b010c6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - numpy
    - pythonocc-core >=7.4
    - python-gmsh
    - pyvista >=0.24.1
    - meshio[all] >=4,<=5.1.2
    - python >=3.5

test:
  imports:
    - gmshModel

about:
  home: https://github.com/NEFM-TUDresden/GmshModel
  summary: A mesh modeling interface to the Gmsh-Python-API
  license:  GPL-3.0-or-later
  license_file: LICENSE
  license_family: GPL
  doc_url: https://gmshmodel.readthedocs.io/
  dev_url: https://github.com/NEFM-TUDresden/GmshModel

extra:
  recipe-maintainers:
    - PhilippMetsch
