{% set name = "gmshmodel" %}
{% set version = "1.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gmshModel-{{ version }}.tar.gz
  sha256: 3ef9d59750acc7c73d5322ed5fb16e056147808691a762a890bf214c1ddd90c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - gmsh
    - meshio >=4,<=5.1.2
    - pyvista >=0.24.1

test:
  imports:
    - gmshModel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NEFM-TUDresden/GmshModel
  summary: A mesh modeling interface to the Gmsh-Python-API
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
